name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TEST_NPM_TOKEN }}
      - name: install
        run: yarn install
      - name: test
        run: yarn test
      - name: build
        run: yarn build
      - name: publish
        run: |
          cat $NPM_CONFIG_USERCONFIG
          echo $NODE_AUTH_TOKEN
          npm publish --access public
